### ISSUE TITLE
globalScope command does not work in repl mode

### ISSUE THREAD

**Issue by toeklk** [gsdlab/ClaferChocoIG#5]
This is claferchocoIG 0.3.9 on mac os x

```
 java -jar ~/install/clafer/claferchocoig.jar --minint 0 --maxint 127 --repl --prettify --file simplePerson.cfr 
Clafer Choco Instance Generator and Multi-Objective Optimizer
Compiling the Clafer model...
Type 'help' for the list of available REPL commands

=== Instance 1 Begin ===

c0_Alice#0
    c0_age#0 = 18
    c0_maritalStatus#0
        c0_married#0
            c0_spouse#0 = c0_Bob#0
c0_Bob#0
    c0_age#1 = 18
    c0_maritalStatus#1
        c0_married#1
            c0_spouse#1 = c0_Alice#0
c0_Carol#0
    c0_age#2 = 5
    c0_maritalStatus#2
        c0_neverMarried#0
--- Instance 1 End ---


claferChocoIG> globalScope 10
Global scope: globalScope 10
Message: null
java.lang.IllegalArgumentException
	at org.clafer.common.Check.noNullsNotEmpty(Check.java:90)
	at org.clafer.compiler.ClaferMultiObjectiveOptimizerGIA.<init>(ClaferMultiObjectiveOptimizerGIA.java:39)
	at org.clafer.compiler.ClaferCompiler.compile(ClaferCompiler.java:256)
	at org.clafer.compiler.ClaferCompiler.compile(ClaferCompiler.java:226)
	at REPL.compileModel(REPL.java:448)
	at REPL.runREPL(REPL.java:224)
	at Main.main(Main.java:117)
```
Some other commands work just fine
```
claferChocoIG> maxInt 10
Max Integer: maxInt 10
Model is ready after the scope change
````
But those related to the global scope seem to fail all
```
claferChocoIG> incGlobalScope 1
Increase global scope: incGlobalScope 1
Message: null
java.lang.IllegalArgumentException
	at org.clafer.common.Check.noNullsNotEmpty(Check.java:90)
	at org.clafer.compiler.ClaferMultiObjectiveOptimizerGIA.<init>(ClaferMultiObjectiveOptimizerGIA.java:39)
	at org.clafer.compiler.ClaferCompiler.compile(ClaferCompiler.java:256)
	at org.clafer.compiler.ClaferCompiler.compile(ClaferCompiler.java:226)
	at REPL.compileModel(REPL.java:448)
	at REPL.runREPL(REPL.java:252)
	at Main.main(Main.java:117)
```

**Comment by JLiangWaterloo** [comment]
The REPL code is calling the MOO compiler and the MOO compiler is complaining that there are no objectives to optimize (I'll make the error message friendlier)

The REPL code should be calling the normal compiler since I don't see any objectives in your model.

**Comment by mantkiew** [comment]
Actually, REPL calls the compiler properly:

```
if (objectives.length == 0)
    	solver = ClaferCompiler.compile(model, scope, compilerOption);
else
            solver = ClaferCompiler.compile(model, scope, objectives, compilerOption);
```

**Comment by JLiangWaterloo** [comment]
Not on this line of the stacktrace though:
https://github.com/gsdlab/ClaferChocoIG/blob/4fd54a114e1f7684f083a64907400b90af28b375/src/main/java/REPL.java#L448

**Comment by mantkiew** [comment]
ok! Easy fix then. I realized that later looking at the exception more carefully.
